ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

#COPY java.log /tmp/java.log

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
